# Overrides applied after upstream dawn-ci.cmake.
# cmake -C dawn/.github/workflows/dawn-ci.cmake -C .github/workflows/dawn-ci.cmake ...
set(DAWN_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
set(DAWN_BUILD_BENCHMARKS OFF CACHE BOOL "" FORCE)
set(DAWN_SUPPORTS_GLFW_FOR_WINDOWING OFF CACHE BOOL "" FORCE)
set(DAWN_USE_GLFW OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_DESKTOP_GL OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_OPENGLES OFF CACHE BOOL "" FORCE)
set(TINT_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(TINT_BUILD_CMD_TOOLS OFF CACHE BOOL "" FORCE)
set(TINT_BUILD_IR_BINARY OFF CACHE BOOL "" FORCE)

if (WIN32)
  set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "Embedded" CACHE STRING "" FORCE)
  set(CMAKE_POLICY_CMP0141 NEW CACHE STRING "" FORCE)
  set(DAWN_BUILD_MONOLITHIC_LIBRARY SHARED CACHE STRING "" FORCE)
elseif (CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  set(DAWN_USE_WAYLAND ON CACHE BOOL "" FORCE)
endif ()
